=== SpiNNakerManchester/PACMAN/pacman/operations/algorithms_metadata_schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
		targetNamespace="https://github.com/SpiNNakerManchester/PACMAN"
		xmlns="https://github.com/SpiNNakerManchester/PACMAN"
		xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="algorithms">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="algorithm" type="Algorithm"
					maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Algorithm">
		<xs:sequence>
			<xs:choice>
				<xs:element name="command_line_args" type="ArgList" />
				<xs:sequence>
					<xs:element name="python_module" type="xs:token" />
					<xs:choice>
						<xs:element name="python_class" type="xs:token" />
						<xs:element name="python_function" type="xs:token" />
					</xs:choice>
				</xs:sequence>
			</xs:choice>
			<xs:element name="input_definitions" type="ParameterDefs" />
			<xs:element name="required_inputs" type="ParamSet" minOccurs="0" />
			<xs:element name="optional_inputs" type="ParamSet" minOccurs="0" />
			<xs:element name="outputs" type="ResultList" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:token" use="required"/>
	</xs:complexType>
	<xs:complexType name="ParameterDefs">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="parameter">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="param_name" type="xs:token" />
						<xs:element name="param_type" type="xs:token"
							minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ParamSet">
		<xs:sequence maxOccurs="unbounded">
			<xs:choice>
				<xs:element name="param_name" type="xs:token"/>
				<xs:element name="all_of" type="ParamSet" />
				<xs:element name="one_of" type="ParamSet" />
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ResultList">
		<xs:sequence>
			<xs:element name="param_type" type="Result"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Result">
		<xs:simpleContent>
			<xs:extension base="xs:token">
				<xs:attribute name="file_name_type" type="xs:token" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="ArgList">
		<xs:sequence>
			<xs:element name="arg" type="xs:string"
				minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== SpiNNakerManchester/PACMAN/unittests/test_algos.xml
<algorithms xmlns="https://github.com/SpiNNakerManchester/PACMAN"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="https://github.com/SpiNNakerManchester/PACMAN
			https://raw.githubusercontent.com/SpiNNakerManchester/PACMAN/master/pacman/operations/algorithms_metadata_schema.xsd">
    <algorithm name="SimpleExternal">
        <command_line_args>
            <arg>/bin/sh</arg>
            <arg>-c</arg>
            <arg>echo foo &gt;{target_file}</arg>
        </command_line_args>
        <input_definitions>
            <parameter>
                <param_name>target_file</param_name>
                <param_type>ExampleFilePath</param_type>
            </parameter>
        </input_definitions>
        <required_inputs>
            <param_name>target_file</param_name>
        </required_inputs>
        <outputs>
            <param_type file_name_type="ExampleFilePath">
                Foo
            </param_type>
        </outputs>
    </algorithm>
    <algorithm name="FailingExternal">
        <command_line_args>
            <arg>/bin/sh</arg>
            <arg>-c</arg>
            <arg>echo foo &gt;{target_file}; echo bar >&amp;2; exit 1</arg>
        </command_line_args>
        <input_definitions>
            <parameter>
                <param_name>target_file</param_name>
                <param_type>ExampleFilePath</param_type>
            </parameter>
        </input_definitions>
        <required_inputs>
            <param_name>target_file</param_name>
        </required_inputs>
        <outputs>
            <param_type file_name_type="ExampleFilePath">
                Foo
            </param_type>
        </outputs>
    </algorithm>
</algorithms>

=== SpiNNakerManchester/PACMAN/pacman/utilities/file_format_converters/converter_algorithms_metadata.xml
<!--
# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 -->
<algorithms xmlns="https://github.com/SpiNNakerManchester/PACMAN"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="https://github.com/SpiNNakerManchester/PACMAN
			https://raw.githubusercontent.com/SpiNNakerManchester/PACMAN/master/pacman/operations/algorithms_metadata_schema.xsd">
    <algorithm name="ConvertToJavaMachine">
        <python_module>pacman.utilities.file_format_converters.convert_to_java_machine</python_module>
        <python_class>ConvertToJavaMachine</python_class>
        <input_definitions>
            <parameter>
                <param_name>machine</param_name>
                <param_type>MemoryMachine</param_type>
            </parameter>
            <parameter>
                <param_name>file_path</param_name>
                <param_type>JsonMachinePath</param_type>
            </parameter>
        </input_definitions>
        <required_inputs>
            <param_name>machine</param_name>
            <param_name>file_path</param_name>
        </required_inputs>
        <outputs>
            <param_type>JsonMachine</param_type>
        </outputs>
    </algorithm>
</algorithms>
